apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservationactor-service
  namespace: default
  labels:
    app: reservationactor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservationactor-service
  template:
    metadata:
      labels:
        app: reservationactor-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "reservationactor-service"
        dapr.io/app-port: "80"
        dapr.io/log-level: "info"
        dapr.io/config: "tracing"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
    spec:
      containers:
      - name: reservationactor-service
        image: davidebedin/sample.microservice.reservationactor:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always