apiVersion: apps/v1
kind: Deployment
metadata:
  name: customization-service
  namespace: default
  labels:
    app: customization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customization-service
  template:
    metadata:
      labels:
        app: customization-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "customization-service"
        dapr.io/app-port: "80"
        dapr.io/config: "tracing"
        dapr.io/sidecar-liveness-probe-period-seconds: "20"
        dapr.io/sidecar-readiness-probe-period-seconds: "20"
    spec:
      containers:
      - name: customization-service
        image: daprk8scrdb.azurecr.io/sample.microservice.customization:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always