controller:
  podAnnotations:
    dapr.io/enabled: "true" 
    dapr.io/app-id: "nginx-ingress" 
    dapr.io/app-protocol: "http"
    dapr.io/app-port: "80"
    dapr.io/log-level: "info"
    dapr.io/config: "tracing"
    dapr.io/sidecar-listen-addresses: "0.0.0.0"